[package]
name = "AoC2024"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
nom = "8.0.0-alpha2"
log = "0.4.22"
pathfinding = "4.12.0"
cached = "0.54.0"
bytemuck = "1.21.0"
flume = "0.11.1"
env_logger = "0.11.6"
wasm-bindgen-futures = "0.4.49"
wgpu = "22.0"
pollster = "0.4.0"
oneshot = "0.1.8"

[[bench]]
name = "my_benchmark"
harness = false
path="benches/my_benchmark.rs"
