[package]
name = "AoC2024"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
nom = "8.0.0-alpha2"
log = "0.4.22"
plotters = "0.3.7"
image = "0.24.9"

[[bench]]
name = "my_benchmark"
harness = false
path="benches/my_benchmark.rs"