[workspace]
members = [
    "src/aoc_utils",
    "src/day*"
]

[package]
name = "AoC2024"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
divan = "0.1.17"

[dependencies]
day00 = { path = "src/day00 - Project setup" }
day01 = { path = "src/day01 - Historian Hysteria" }
day02 = { path = "src/day02 - Red Nosed Reports" }
day03 = { path = "src/day03 - Mull It Over" }
day04 = { path = "src/day04 - Ceres Search" }
day05 = { path = "src/day05 - Print Queue" }
day06 = { path = "src/day06 - Guard Gallivant" }
day07 = { path = "src/day07 - Bridge Repair" }
day08 = { path = "src/day08 - Resonant Collinearity" }
day09 = { path = "src/day09 - Disk Fragmenter" }
day10 = { path = "src/day10 - Hoof It" }
day11 = { path = "src/day11 - Plutonian Pebbles" }
day12 = { path = "src/day12 - Garden Groups" }
day13 = { path = "src/day13 - Claw Contraption" }
day14 = { path = "src/day14 - Restroom Redoubt" }
day15 = { path = "src/day15 - Warehouse Woes" }
day16 = { path = "src/day16 - Reindeer Maze" }
day17 = { path = "src/day17 - Chronospatial Computer" }
day18 = { path = "src/day18 - RAM Run" }
day19 = { path = "src/day19 - Linen Layout" }
day20 = { path = "src/day20 - Race Condition" }
day21 = { path = "src/day21 - Keypad Conundrum" }
day22 = { path = "src/day22 - Monkey Market" }
day23 = { path = "src/day23 - Lan Party" }
day24 = { path = "src/day24 - Crossed Wires" }
day25 = { path = "src/day25 - Code Chronicle" }

[[bench]]
name = "my_benchmark"
harness = false
path="benches/my_benchmark.rs"

